New font and FF CSS

diff --git a/bin/wal b/bin/wal
--- a/bin/wal
+++ b/bin/wal
@@ -5,6 +5,7 @@
 # Created by Dylan Araps
 
 # Speed up script by not using unicode.
+sys_locale="$LANG"
 export LC_ALL=C
 export LANG=C
 
@@ -12,9 +13,10 @@ shopt -s nullglob nocasematch
 
 # Internal variables.
 cache_dir="${HOME}/.cache/wal"
+pid_file="${cache_dir}/wal.pid"
 newline=$'\n'
 color_count=16
-
+os="$(uname)"
 
 # GENERATE COLORSCHEME
 
@@ -46,30 +48,33 @@ rand_img() {
 }
 
 get_colors() {
-    # Check for imagemagick.
-    if ! type -p convert >/dev/null 2>&1; then
-        out "error: imagemagick not found, exiting..."
-        out "error: wal requires imagemagick to function."
-        exit 1
+    # Only run if -i used, skip for -f since $wal not set and $cache_file already set.
+    if [[ -n "$wal" ]]; then
+        # Check for imagemagick.
+        if ! type -p convert >/dev/null 2>&1; then
+            out "error: imagemagick not found, exiting..."
+            out "error: wal requires imagemagick to function."
+            exit 1
+        fi
+
+        # Create colorscheme dir.
+        mkdir -p "${cache_dir}/schemes"
+
+        # Get the current wallpaper.
+        [[ -f "${cache_dir}/wal" ]] && old_wall="$(< "${cache_dir}/wal")"
+
+        # Shuffle the image.
+        [[ -d "$wal" ]] && rand_img
+
+        # If the wallpaper doesn't exist, use the current one.
+        [[ ! -f "$wal" ]] && wal="$old_wall"
+
+        # Store cached colorscheme as 'dir-to-img.jpg'
+        cache_file="${cache_dir}/schemes/${wal//\//_}"
+
+        # Cache the wallpaper name
+        printf "%s\n" "$wal" > "${cache_dir}/wal"
     fi
-
-    # Create the cache dir.
-    mkdir -p "${cache_dir}/schemes"
-
-    # Get the current wallpaper.
-    [[ -f "${cache_dir}/wal" ]] && old_wall="$(< "${cache_dir}/wal")"
-
-    # Shuffle the image.
-    [[ -d "$wal" ]] && rand_img
-
-    # If the wallpaper doesn't exist, use the current one.
-    [[ ! -f "$wal" ]] && wal="$old_wall"
-
-    # Store cached colorscheme as 'dir-to-img.jpg'
-    cache_file="${cache_dir}/schemes/${wal//\//_}"
-
-    # Cache the wallpaper name
-    printf "%s\n" "$wal" > "${cache_dir}/wal"
 
     # Generate 16 colors from the image and save them to a file.
     if [[ -f "$cache_file" ]]; then
@@ -82,6 +87,9 @@ get_colors() {
             colors=($(convert "${wal}"  +dither -colors "$((color_count + ${index:-2}))" -unique-colors txt:- | grep -E -o " \#.{6}"))
             ((index++))
             out "colors: Imagemagick couldn't generate a $color_count color palette, trying a larger palette size ($((color_count + index)))."
+
+            # Quit the loop if we're taking too long.
+            ((index == 10)) && break
         done
 
         # Cache the scheme.
@@ -97,24 +105,38 @@ get_colors() {
 
 set_color() {
     sequences+="\033]4;${1};${2}\007"
-    x_colors+="*color${1}: ${2}${newline}"
     sh_colors+="color${1}='${2}'${newline}"
     scss_colors+="\$color${1}: ${2};${newline}"
+    firefox_colors+="  --color${1}: ${2};${newline}"
+    putty_colors+="\"Colour${1}\"=\"$(convert_to_rgb "${2}")\"${newline}"
+
+    # Set *.color and *color to fix issues with Polybar.
+    x_colors+="*color${1}: ${2}${newline}"
+    x_colors+="*.color${1}: ${2}${newline}"
+
     plain+="${2}${newline}"
 }
 
 set_special() {
     sequences+="\033]${1};${2}\007"
 
-    # Fix termite foreground bold
-    # sequences+="\033]1;${colors[15]}\007"
-
     # Set X colors
     case "$1" in
-        10) x_colors+="*foreground: ${2}${newline}" ;;
-        11) x_colors+="*background: ${2}${newline}" ;;
-        12) x_colors+="*cursor: ${2}${newline}" ;;
-  esac
+        10)
+            x_colors+="URxvt*foreground: ${2}${newline}"
+            x_colors+="XTerm*foreground: ${2}${newline}"
+        ;;
+
+        11)
+            x_colors+="URxvt*background: ${2}${newline}"
+            x_colors+="XTerm*background: ${colors[0]}${newline}"
+        ;;
+
+        12)
+            x_colors+="URxvt*cursorColor: ${2}${newline}"
+            x_colors+="XTerm*cursorColor: ${colors[0]}${newline}"
+        ;;
+    esac
 }
 
 send_sequences() {
@@ -129,23 +151,36 @@ send_sequences() {
     [[ "$vte" != "on" ]] && set_special 708 "${alpha:+[${alpha}]}${colors[0]}"
 
     set_color 0  "${colors[0]}"
-    set_color 1  "${colors[9]}"
-    set_color 2  "${colors[10]}"
-    set_color 3  "${colors[11]}"
-    set_color 4  "${colors[12]}"
-    set_color 5  "${colors[13]}"
-    set_color 6  "${colors[14]}"
-    set_color 7  "${colors[15]}"
 
-    # Create a comment color based on the brightness of the background.
-    case "${colors[0]:1:1}" in
-        [0-1]) set_color 8 "#666666" ;;
-        2)     set_color 8 "#757575" ;;
-        [3-4]) set_color 8 "#999999" ;;
-        5)     set_color 8 "#8a8a8a" ;;
-        [6-9]) set_color 8 "#a1a1a1" ;;
-        *)     set_color 8 "${colors[7]}" ;;
-    esac
+    # If $extended_colors isn't set, only use the bright colors.
+    if [[ -z "$extended_colors" ]]; then
+        set_color 1  "${colors[9]}"
+        set_color 2  "${colors[10]}"
+        set_color 3  "${colors[11]}"
+        set_color 4  "${colors[12]}"
+        set_color 5  "${colors[13]}"
+        set_color 6  "${colors[14]}"
+        set_color 7  "${colors[15]}"
+
+        # Create a comment color based on the brightness of the background.
+        case "${colors[0]:1:1}" in
+            [0-1]) set_color 8 "#666666" ;;
+            2)     set_color 8 "#757575" ;;
+            [3-4]) set_color 8 "#999999" ;;
+            5)     set_color 8 "#8a8a8a" ;;
+            [6-9]) set_color 8 "#a1a1a1" ;;
+            *)     set_color 8 "${colors[7]}" ;;
+        esac
+    else  # $extended_colors="on"
+        set_color 1  "${colors[1]}"
+        set_color 2  "${colors[2]}"
+        set_color 3  "${colors[3]}"
+        set_color 4  "${colors[4]}"
+        set_color 5  "${colors[5]}"
+        set_color 6  "${colors[6]}"
+        set_color 7  "${colors[7]}"
+        set_color 8  "${colors[8]}"
+    fi
 
     set_color 9  "${colors[9]}"
     set_color 10 "${colors[10]}"
@@ -155,56 +190,67 @@ send_sequences() {
     set_color 14 "${colors[14]}"
     set_color 15 "${colors[15]}"
 
+    # Set a black color that isn't affected by bold highlighting.
+    sequences+="\033]4;66;${colors[0]}\007"
+    x_colors+="*color66: ${colors[0]}${newline}"
+
     # Directing output to /dev/pts/* allows you to send output to all open terminals
     # on your system.
     for term in /dev/pts/[0-9]*; do
-        printf "%b" "$sequences" > "$term" &
+        [[ -w "$term" ]] && printf "%b" "$sequences" > "$term" &
     done
 
     out "colors: Set terminal colors"
 }
 
 set_wallpaper() {
-    # Get desktop environment.
-    de="${XDG_CURRENT_DESKTOP}"
+    if [[ -z "$nowall" ]]; then
+        # Get desktop environment.
+        de="${XDG_CURRENT_DESKTOP}"
 
-    # Fallback to using xprop.
-    [[ -z "$de" ]] && type -p xprop >/dev/null 2>&1 && \
-        de="$(xprop -root | awk '/KDE_SESSION_VERSION|^_MUFFIN|xfce4|xfce5/')"
+        # Fallback to using xprop.
+        [[ -z "$de" ]] && type -p xprop >/dev/null 2>&1 && \
+            de="$(xprop -root | awk '/KDE_SESSION_VERSION|^_MUFFIN|xfce4|xfce5/')"
 
-    case "$de" in
-        *"MUFFIN"* | *"Cinnamon"*) gsettings set org.cinnamon.desktop.background picture-uri "file://${wal}" ;;
-        *"MATE"*) gsettings set org.mate.background picture-filename "$wal" ;;
-        *"GNOME"*) gsettings set org.gnome.desktop.background picture-uri "file://${wal}" ;;
+        case "$de" in
+            *"MUFFIN"* | *"Cinnamon"*) gsettings set org.cinnamon.desktop.background picture-uri "file://${wal}" ;;
+            *"MATE"*) gsettings set org.mate.background picture-filename "$wal" ;;
+            *"GNOME"*) gsettings set org.gnome.desktop.background picture-uri "file://${wal}" ;;
 
-        *"XFCE"*)
-            xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set "$wal" 2>/dev/null ||\
-            xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set "$wal" 2>/dev/null
-        ;;
+            *"XFCE"*)
+                xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set "$wal" 2>/dev/null
+                xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set "$wal" 2>/dev/null
+            ;;
 
-        *)
-            if type -p feh >/dev/null; then
-                feh --bg-fill "$wal"
+            *)
+                if type -p feh >/dev/null; then
+                    feh --bg-fill "$wal"
 
-            elif type -p nitrogen >/dev/null; then
-                nitrogen --set-zoom-fill "$wal"
+                elif type -p nitrogen >/dev/null; then
+                    nitrogen --set-zoom-fill "$wal"
 
-            elif type -p bgs >/dev/null; then
-                bgs "$wal"
+                elif type -p bgs >/dev/null; then
+                    bgs "$wal"
 
-            elif type -p hsetroot >/dev/null; then
-                hsetroot -fill "$wal"
+                elif type -p hsetroot >/dev/null; then
+                    hsetroot -fill "$wal"
 
-            elif type -p habak >/dev/null; then
-                habak -mS "$wal"
+                elif type -p habak >/dev/null; then
+                    habak -mS "$wal"
 
-            else
-                gsettings set org.gnome.desktop.background picture-uri "file://${wal}"
-            fi
-        ;;
-    esac
+                elif [[ "$os" == "Darwin" ]]; then
+                    osascript -e 'tell application "Finder" to set desktop picture to POSIX file "'"${wal/#\~/$HOME}"\"
 
-    out "wallpaper: Set new wallpaper"
+                else
+                    gsettings set org.gnome.desktop.background picture-uri "file://${wal}"
+                fi
+            ;;
+        esac
+
+        out "wallpaper: Set new wallpaper"
+    else
+        out "wallpaper: '-n' was used, skipping wallpaper"
+    fi
 }
 
 
@@ -226,7 +272,13 @@ export_scss() {
     out "export: Exported scss color variables"
 }
 
+export_firefox() {
+    printf "%s\n" ":root {${newline}${firefox_colors}}"
+    out "export: Exported Firefox color variables"
+}
+
 export_rofi() {
+
     rofi_bg="argb:${alpha:-FF}${colors[0]/\#}"
     rofi_bg_alt="argb:00000000"
 
@@ -243,25 +295,47 @@ export_rofi() {
     x_colors+="rofi.color-urgent: ${rofi_bg_alt}, ${colors[15]}, ${rofi_bg_alt}, ${rofi_bg_alt}, ${colors[14]}${newline}"
 }
 
+export_emacs() {
+    x_colors+="emacs*background: ${colors[0]}${newline}"
+    x_colors+="emacs*foreground: ${colors[15]}${newline}"
+}
+
 export_plain() {
     printf "%s" "$plain"
     out "export: Exported plain colors"
+}
+
+export_putty() {
+    printf "%s\n\n" "Windows Registry Editor Version 5.00"
+    printf "%s\n" "[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\Wal]"
+    printf "%s" "$putty_colors"
+    out "export: Exported putty colors"
+}
+
+export_xrdb() {
+    printf "%s" "$x_colors"
+    out "export: Exported xrdb colors"
 }
 
 export_colors() {
     export_sequences > "${cache_dir}/sequences"
     export_envar     > "${cache_dir}/colors.sh"
     export_scss      > "${cache_dir}/colors.scss"
-    export_rofi      > "${cache_dir}/rofi"
+    export_firefox   > "${cache_dir}/firefox.css"
+    export_rofi
+    export_emacs
     export_plain     > "${cache_dir}/colors"
+    export_xrdb      > "${cache_dir}/colors.xresources"
+    export_putty     > "${cache_dir}/colors.reg"
 }
 
 
 # RELOAD COLORSCHEME
 
+
 reload_colors() {
     # Source the current sequences
-    sequences="$(< "${HOME}/.cache/wal/sequences")"
+    sequences="$(< "${cache_dir}/sequences")"
 
     # If vte mode was used, remove the problem sequence.
     [[ "$vte" == "on" ]] && sequences="${sequences/??\]708\;\#??????}"
@@ -284,7 +358,36 @@ reload_xrdb() {
         out "colors: Merged colors with X env"
 }
 
+
 # OTHER
+
+
+convert_to_rgb() {
+    red="$((16#${1:1:2}))"
+    green="$((16#${1:3:2}))"
+    blue="$((16#${1:5:2}))"
+
+    printf "%s" "${red},${green},${blue}"
+}
+
+cleanup_pid () {
+    rm "$pid_file"
+}
+
+kill_old_wal () {
+    # Create Cache Dir
+    mkdir -p "${cache_dir}/"
+
+    # Kill old 'wal' instances found at $pid_file.
+    if [[ -f "$pid_file" ]]; then
+      old_pid="$(< "${pid_file}")"
+      pkill -TERM -P "$old_pid" 2>/dev/null
+      kill "$old_pid" 2>/dev/null
+    fi
+
+    # Log our pid into the file
+    printf "%s" "$$" > "$pid_file"
+}
 
 get_full_path() {
     # Go to the relative PATH.
@@ -320,22 +423,30 @@ Example: wal -i '${HOME}/Pictures/Wallpapers/'
 Flags:
   -a                      Set terminal background transparency. *Only works in URxvt*
   -c                      Delete all cached colorschemes.
+  -f '/path/to/colors'    Load colors directly from a colorscheme file.
   -h                      Display this help page.
   -i '/path/to/dir'       Which image to use.
      '/path/to/img.jpg'
+  -n                      Skip setting the wallpaper.
   -o 'script_name'        External script to run after 'wal'.
   -q                      Quiet mode, don't print anything.
   -r                      Reload current colorscheme.
   -t                      Fix artifacts in VTE Terminals. (Termite, xfce4-terminal)
+  -x                      Use extended 16-color palette.
 
 "
 }
 
 get_args() {
-    while getopts ":a:chi:o:qrt" opt; do
+    while getopts ":a:cf:hi:no:qrtx" opt; do
         case "$opt" in
             "a") alpha="$OPTARG" ;;
             "c") rm -rf "${cache_dir}/schemes"; exit ;;
+            "f")
+                [[ -f "$OPTARG" ]] && cache_file="$OPTARG"
+                [[ -z "$cache_file" ]] && cache_file="$(get_full_path "$OPTARG")"
+                nowall="on"
+            ;;
             "h") usage; exit 1 ;;
 
             "i")
@@ -343,10 +454,12 @@ get_args() {
                 [[ -z "$wal" ]] && wal="$(get_full_path "$OPTARG")"
             ;;
 
+            "n") nowall="on" ;;
             "o") external_script=("$OPTARG") ;;
             "q") quiet="on" ;;
             "r") reload="on" ;;
             "t") vte="on" ;;
+            "x") extended_colors="on" ;;
 
             "?")
                 printf "%s\n" "Invalid option: -$OPTARG" >&2
@@ -364,8 +477,8 @@ get_args() {
     [[ "$reload" == "on" ]] && reload_colors
 
     # Check if -i was used.
-    if [[ -z "$wal" ]]; then
-        printf "%s\n" "Error: 'wal' must be run with '-i'" >&2
+    if [[ -z "$wal" && -z "$cache_file" || -n "$wal" && -n "$cache_file" ]]; then
+        printf "%s\n" "Error: 'wal' must be run with either '-i' or '-f'" >&2
         printf "%s\n" "Try 'wal -h' for more information." >&2
         exit 1
     fi
@@ -377,27 +490,24 @@ get_args() {
 
 main () {
     get_args "$@"
+    kill_old_wal
 
-    # Get 16 unique colors from the image.
     get_colors
-
-    # Send the color changing sequences to every open terminal emulator.
     send_sequences
-
-    # Set the wallpaper.
     set_wallpaper
-
-    # Export the colors in other formats.
     export_colors
-
-    # Merge colors into X env.
     reload_xrdb
-
-    # Reload env
     reload_env >/dev/null 2>&1
 
+    # Set the locale back to the original value.
+    export LC_ALL="$sys_locale"
+
     # Execute custom script.
-    type -p "${external_script[0]}" >/dev/null 2>&1 && "${external_script[@]}"
+    [[ "${external_script[0]}" ]] && bash -c "${external_script[@]}"
+
+    cleanup_pid
+
 }
 
 main "$@"
+
